### ISSUE TITLE
How to make QuickViewer available in your language

### ISSUE THREAD

**Issue by kanryu** [kanryu/quickviewer#11]
I wrote it on a [wiki](https://github.com/kanryu/quickviewer/wiki).

If you are interested in it, please cooperate.
You can create it even if you are not a software engineer :)

**Comment by LRN** [comment]
You should clarify that you need someone who knows Japanese _and_ English. Because current English localization is bad - which not only makes the program less pleasing to use if you're using this language, but also hinders the ability of other people to translate it, because it's often very unclear what the English text in QuickViewer actually _means_. So the first order of business should be to improve English strings.

**Comment by kanryu** [comment]
Thanks.

As you guess I am not a native English speaker, so it will not be difficult for others to read and understand English. 

English notation and Japanese notation are equally positive in QuickViewer, I translate directly. In this development there has been a collaborator for quite a while, he is working on translation and suggesting better expression by pointing out the bad parts in QuickViewer's English notation.

But since such work is limited to a small portion of the whole, there will still be plenty of bad English expressions left to you.

English expression should be improved by English speakers. Since I add comments to the expressions of each application, why should I change the expression accordingly?

Some have already been included in 0.8.3.

**Comment by kanryu** [comment]
Here, a file for translation work is prepared. If you are interested in making QuickViewer English better, you can add it to this file.

[Wiki/translation-en](https://github.com/kanryu/quickviewer/wiki/translation-en)

**Comment by kanryu** [comment]
@LRN 
I asked a translator to make a new English translation :)

**Comment by dragons4life** [comment]
I've modified the spanish and english translation a bit, some things I didn't quite understood so I left them as is, spanish translation doesn't have tilde(s).
[section0023]
context=DatabaseSettingDialog
comment=Caption of FolderSelectDialog urging selection of folders containing Images and Archives
en=Please select a folder containing Images or Archives
es=Por favor selecciona una carpeta que incluya imágenes o carpetas
tran=

Is the meaning of Archives here for subfolders or folders?

[section0033]
context=ExifDialog
comment=JPEG EXIF Orientation of the main body of the camera(2)
en=Mirror horizontal
es=Inversión
tran=
What does this mean? Mirrored Horizontally?

[section0051]
context=FolderItemModel
comment=Title of the column in the folder list when displaying as an independent Window in Folder Window
en=UpDate
es=día y hora reconducción

UpDate? you mean by date modified or by date? by how much you have read? last time modified?

[section0104]
context=MainWindow
comment=Function to switch windows to maximize or normal display
en=&Maximize or Normal
es=&Máximo o Normal

Fullscreen or Restore?

[section0137]
context=MainWindow
comment=In the case of a digital book, since the first image is a cover page, only one image is displayed
en=Always open &first images even withas only one page
es=Primera imagen abiertos como una vista(&F)
tran=

[section0143]
context=MainWindow
comment=Functions to be used when the Volume title in the catalog is long
en=Larger &grid to display long title
es=Para vizualizar un título largo, tenga el bastidor &grande
tran=

Don't understand these, the comment says it only displays the cover of the digital book? any examples?

I've gone ahead and changed shaders to scalers, almost tempted to remove "Interpolation" from bicubic, though I am wondering why there is 4 different bicubic scalers ( or maybe keeping shader and changing interpolation to scaler?)
added .gif .webp .cbz to openfilefolder

**It seems that lanczos scaler/shader is in here but no way to activate it on your program.** unless is named wrong.

What does (Quality) mean on Bicubic?

Anyways, I am a bit confuse in some of the things on here, but I update the english and spanish translation, if anyone is willing to test. 

https://paste.ubuntu.com/25849586/

**Comment by kanryu** [comment]
Thank you very much! :)

> en=Mirror horizontal
> es=Inversión
> tran=
> What does this mean? Mirrored Horizontally?
Exif's rotation has 8 options, including 'Mirror horizontal' in it.
This means a picture whose horizontal orientation is reversed horizontally.

> comment=Title of the column in the folder list when displaying as an independent Window in Folder Window
> en=UpDate
> es=día y hora reconducción
> UpDate? you mean by date modified or by date? by how much you have read? last time modified?
Yes.
This is an option to sort the list of files displayed in the folder window (yellow icon on the toolbar).
It is like this because it requires a very short expression for its convenience. It should be an icon.

> context=MainWindow
> comment=Function to switch windows to maximize or normal display
> en=&Maximize or Normal
> es=&Máximo o Normal
> Fullscreen or Restore?
No.
This menu switches the window to maximize display and normal display.

> comment=Functions to be used when the Volume title in the catalog is long
> en=Larger &grid to display long title
> es=Para vizualizar un título largo, tenga el bastidor &grande
> tran=
> Don't understand these, the comment says it only displays the cover of the digital book? any examples?
When you create and display the Catalog, change the size of the display area per book.
Often the title of the book will be long. Switch this with this option when it can not be displayed.

> I've gone ahead and changed shaders to scalers, almost tempted to remove "Interpolation" from bicubic, though I am wondering why there is 4 different bicubic scalers ( or maybe keeping shader and changing interpolation to scaler?)
Please do not remove "Interpolation". This is because options other than interpolation may be added in the future.
QuickViewer has three 'Bicubic' options.

- Bicubic interpolation (slow)
    - Bicubic with by OpenGL fragment shader(it hasn't been used)
- CPU Bicubic interpolation
    - Currently the highest quality option
- CPU Bicubic after GPU Bilinear(standard)
    - 'CPU Bicubic interpolation' takes time to process (sometimes there are cases), so switch it after displaying with normal bilinear interpolation until processing is completed.

> It seems that lanczos scaler/shader is in here but no way to activate it on your program. unless is named wrong.
That's a good question :)
QuickViewer is currently not used because it is being built with settings that do not use OpenGL. However, it is left as it is because it may be used again. This is a performance reason (because using OpenGL instead slows down the display)

Overall, the translation file posted on the wiki is outdated.
If possible, edit the ts file directly with QtLingist.
https://github.com/kanryu/quickviewer/blob/master/QuickViewer/translations/Contribution.md

**Comment by dragons4life** [comment]
Thanks I'll look into using that instead however I am stuck on 

1. clone the repository into local. https://github.com/kanryu/quickviewer
Would you mind showing me were to clone the repository with a picture?
Downloaded https://goo.gl/3TZjmW (in Windows) but there is no "Local" folder.

**Comment by kanryu** [comment]
Please read the official manual.
https://help.github.com/articles/cloning-a-repository-from-github/

'Local' refers to somewhere on your PC. It means that it is not on the Internet. If you are a QuickViewer user, this app will be located somewhere in the local.

**Comment by dragons4life** [comment]
Thanks, I am having problems with knowing if the translation was saved or not, for example whenever I translate something it goes back to the untranslated version.

e.g; https://8.lithi.io/qIDu.mp4

**Comment by kanryu** [comment]
@dragons4life Thank you for your efforts to contribute to QuickViewer! :)

First, please check the official manual.
http://doc.qt.io/qt-5/linguist-translators.html

1. Enter a new Spanish translation for the entry
1. Select menu [Translation]-[Done and Next] or tha same icon on toolbar or Ctrl+Enter
1. Then the string entry will be [?] to [checked]
1. Repeat [1] - [3] for all entries you think are necessary
1. Select menu [File]-[Save] to save the ts
1. Select menu [File]-[Release] to release the qm
1. Copy the qm onto "QuickViewer-XXX-x64/translations/", so you can check with QuickViewer!
