### ISSUE TITLE
[Feature Request] Border between pages

### ISSUE THREAD

**Issue by eddiezato** [kanryu/quickviewer#138]
Can you add an option to show border line between pages in 2-page mode? So that the pages didn't show very close, but with a small distance in between. 4-pixel width vertical line of background color, for example.

This will help quickly understand the difference, whether you see 2 portrait pages or 1 landscape page.

**Comment by kanryu** [comment]
I don't think your proposal will produce good results.

That's because capturing a digital scrap always involves up / down / left / right offsets and some rotation, not the regular errors you wrote. Also, the tendency of the error may be different for each scrap volume.

A comprehensive solution is an extension that allows you to save specific two pages of a volume (perhaps a directory or a book) by specifying up / down / left / right translation offsets and small rotations. Progress.ini and thumbnail.sqlite3.db generated by QuickViewer have always been designed to be extensible, but have not been implemented because they have not been focused on until now.

**Comment by eddiezato** [comment]
Sorry, I don't understand the answer. May be it was given for another issue?
I am talking about the border between pages when 2 pages are displayed simultaneously. Here is a picture described my point:

![border](https://user-images.githubusercontent.com/11173476/73669443-0477db00-46da-11ea-8e12-328d9bf7596e.png)
