### ISSUE TITLE
QuickViewer does not open the first image quickly

### ISSUE THREAD

**Issue by LRN** [kanryu/quickviewer#14]
How to reproduce:
- Run QuickViewer with "File->Auto load last used" disabled. Note that the program itself launches rather fast.
- Select "File->Open Image Folder" (misleadingly named, as it also allows single files to be opened).
- Pick a folder full of images, and select one of the images

Expected result:
- The amount of time spent on loading a reasonably-sized image file is small (a couple of hundreds of milliseconds; less than a second in any case) and does not depend on how many other images are in the same folder

Actual result:
- QuickViewer takes a lot of time (up to 3 seconds i my case) to load the first image in a folder of many images

How to fix:
- Prioritize loading the first image, and display it as soon as it is loaded
- Pre-load images in a separate thread. I believe, [this](https://blogs.kde.org/2011/01/22/loading-and-scaling-images-thread) should do the trick. That said, i'd pay special attention to the thread and ensure that it is not destroyed and re-created for every image, but rather re-used every time. You might want to have multiple threads (maybe in a pool) to pre-load multiple images simultaneously.

**Comment by kanryu** [comment]
Hi @LRN  ,

QuickViewer is essentially a viewer that opens folders and archives, not a viewer that opens one image.

Therefore, the current status is initialized in the following order:

1. The PATH of the folder or file is passed to PageManger::loadVolume()
1. PageManager initializes FileVolume and FileLoader
1. FileLoader enumerates all the image files of a folder or an archive
1. If the image file name is specified, open that image, if not specified, open the image with the youngest file name
1.  The images of several pages before and after that are also opened in separate threads (prefetching mechanism)

According to [3], QuickViewer has a freeze time proportional to the number of files in the folder that opens the image.
This time can not be ignored unexpectedly. Enumerating the files contained in a folder is essentially the same as reading a fragmented file.

There are two approaches to speeding up this.

1. Open only one image without enumerating. 
    - Loading images and other images to WorkerThread
1. Stop opening folders and images. 
    - Record the PATH, the number of files, etc. of the last opened image in ini file etc, and substitute it by reading it. The image file to be read may be genuine open, or a cache file stored in a way that it can be read faster

Since the current QuickViewer takes priority that it is portable, it does not generate any cache files. But if we try to speed up it's a good idea to make a cache file.

**Comment by LRN** [comment]
> 1. Open only one image without enumerating.
> 
>    - Loading images and other images to WorkerThread
> 
That seems like a good option. The use-case that i have in mind is QuickViewer just opening new random images that the user just got from somewhere else. So using a cache is not an option here. It should certainly be possible to open an image in isolation, hiding the UI elements (like the slider widget at the bottom) that are related to viewing other images in the folder, until the enumeration is complete.

**Comment by kanryu** [comment]
Since there are more points to be corrected than we imagined, we will set them as future tasks. It will not be realized immediately.

**Comment by kanryu** [comment]
@LRN I made it :)

**Comment by LRN** [comment]
Now (in v0.9.0) the first image is displayed quickly. Switching to other images from the first image is delayed until the processing is finished, but that is not unexpected.

One possible enhancement is to make the processing (or whatever it is that QuickViewer must do before being able to flip images in a folder) more lazy, to allow previous/next image to be shown before the whole folder is finished being processed. But that's not critical.

With the power vested in me by The Secret Society Of Bug Reporters I hereby pronounce this bug fixed.

**Comment by kanryu** [comment]
@LRN 
I made it :)

**Comment by LRN** [comment]
Made what? I don't see any differences between 0.9.0 and 0.9.1, as far as flipping images is concerned.

**Comment by kanryu** [comment]
In v 0.9.1, the operation of enumerating the files of folders after the image reading is completed has been changed. Previously it was simultaneous.

In the case of JPEG, since it is usually less than 100 ms until reading and resizing is completed, there may not be any difference in experience.
In other image formats such as PNG this time will be longer.
