### ISSUE TITLE
Toolbar displaces the image in fullscreen mode

### ISSUE THREAD

**Issue by LRN** [kanryu/quickviewer#15]
How to reproduce:
 - Open an image
 - Enable fullscreen mode
 - Observe that the toolbar at the top is not visible
 - Move the cursor toward the top edge of the screen

Expected result:
 - The toolbar appears along the top edge of the screen, overlaid on top of the image being displayed, the image itself doesn't move at all

Actual result:
 - The toolbar widget, which is a sibling widget packed together with the image, is made visible, and thus it appears, visibly displacing the image, so the image appears to be "jumping" down

Possible fixes:
- Use an overlay to display the toolbar. I don't know whether Qt has overlay widgets though, you'll have to find that for yourself. In GTK you would have used GtkOverlay for this kind of thing. It might be possible to work around this by cleverly replacing the image being displayed with the same image that has some toolbar-sized part of it cut off at the top (in which case existing behaviour, where toolbar is a sibling widget, would not look as if it displaces the image, which fixes this cosmetic bug). But that's just barbaric, in my opinion.
- Alternatively, always display the toolbar in fullscreen mode (thus it won't appear and disappear, preventing this cosmetic bug from being observed). Note that this is not mutually exclusive with existing behaviour (where the toolbar is hidden until the cursor is along the top edge of the screen), you can do both (and also apply the fix described above), and make an option to switch between these two different behaviours.

**Comment by kanryu** [comment]
Implementation is completed, but we have decided to delay release by one day because improvement work in English notation is in the final stage.

**Comment by kanryu** [comment]
@LRN 
I made it :)

**Comment by LRN** [comment]
Well, your solution is quite...unorthodox...I guess it does satisfy the criteria of being a fix for this bug, from a purely technical point of view.

**Comment by kanryu** [comment]
It is a pity that such a reaction will be done despite fully satisfying your request :(

**Comment by LRN** [comment]
*shrugs* I like things to be proper. Anyway, i will not press the issue anymore. If you think that this is really a fix, and not a quick hack to work around the problem, then so be it - you're the developer, i'm not (well, not a developer of _this_ application), so i'm not in a position to reject code just because i think it's inelegant.

**Comment by kanryu** [comment]
Could you explain a little more specifically what you think is appropriate?

**Comment by LRN** [comment]
Something like [this](https://www.youtube.com/watch?v=LRX_E0GpuR8). Around 0:20 the video author switches gedit to fullscreen mode, and then moves the mouse to the top edge, causing the fullscreen version of the headerbar to drop in. That's how overlay toolbar should look. It certainly should not have window decorations.

I'm not asking for fancy drop-in/drop-out animations, mind you - they are certainly not worth the trouble, unless your toolkit already provides them.

**Comment by kanryu** [comment]
The upper frame for the full screen newly added this time is not yet the definite specification.

In v0.8.3, title bar and system button are displayed, but this is for clarity. We should not give users unnecessary surprises. For example, a title bar outside the standard OS. If we provide OS standard UI, users can understand how to use without specific explanation.

If I modify the current code a bit, I can remove the title bar from the upper frame. Only the main menu and toolbar will be left.

The animation occurs when displaying frames because calling showMaximize(), resulting in Windows standard maximized animation.
I do not know how to display the window in the state maximized from the beginning within the scope of Qt. (Possible with Win32 API)

p.s.
There is no known way to add a button to the right side of the QToolbar.

**Comment by kanryu** [comment]
![clipboard01](https://user-images.githubusercontent.com/759165/28667797-fedc7db6-7307-11e7-8ac1-dca372739f8b.jpg)

**Comment by LRN** [comment]
This does look much better. You might also be interested in [this](https://blogs.msdn.microsoft.com/oldnewthing/20121003-00/?p=6423) blog post, about disabling window animations. Another post somewhere also claimed that a window with WS_EX_TOOLWINDOW extended style is not subject to these animations, so that's another lead to pursue.

**Comment by kanryu** [comment]
@LRN 

Thanks.
Unlike normal windows, WS_EX_TOOLWINDOW has only a narrow title bar and close button.
Probably not suitable for this application.

There is no animation when displaying a toolbar without a frame that you just posted.

Currently it is editing the source code so that the same movement is done for the page bar displayed below. Then this library will be published as QFullscreenFrame.
