### ISSUE TITLE
Artifacts when selecting Lanzos interpolation and Bicubic interpolation

### ISSUE THREAD

**Issue by vilmantasr** [kanryu/quickviewer#16]
When selecting Shader / Lanzos interpolation and Bicubic interpolation program shows only (when viewing images):

![quickviewer](https://user-images.githubusercontent.com/8343756/28654175-ee797f36-729a-11e7-9597-aecbc6d61885.png)

QuickViewer 0.8.4, Windows 10, mobile Sandy Bridge proccesor, Intel HD 3000.

**Comment by kanryu** [comment]
Please upload the image before loading it into QuickViewer as it is.

**Comment by vilmantasr** [comment]
![imgp5056](https://user-images.githubusercontent.com/8343756/28654419-d4434136-729c-11e7-9a4b-7a728af0ae75.jpg)

all images shows artifacts, jpg, gif, etc.

**Comment by kanryu** [comment]
Thanks.

First, GPU bicubic and Lanczos interpolation is a function created to improve the display of monochrome images composed of screen tones (usually magazine captures). The image with a tone curve calm like the image of a digital camera is bilinear and there is no problem. If you do not improve with these display methods, please try the following two menus (CPU Bicubic).

Next, QuickViewer uses Direct3D through the OpenGL translator. This requires a graphics driver. Your PC may not have a graphics driver installed.

I think this problem is hardware dependent.

**Comment by vilmantasr** [comment]
![intel](https://user-images.githubusercontent.com/8343756/28654952-e4bfc530-72a0-11e7-9a0c-44036467cbef.png)

Drivers instaled, but yes computer is quite old ;)

**Comment by kanryu** [comment]
@vilmantasr 
I wrote a new article :)

https://kanryu.github.io/quickviewer/shader

**Comment by vilmantasr** [comment]
Thanks, very informative ;)
