### ISSUE TITLE
Make releases you actually can build.

### ISSUE THREAD

**Issue by Arnaudv6** [kanryu/quickviewer#17]
Hello Kanryu and thanks for quickviewer: I was able to try it on Windows at work, and apart from systematic crashes when closing, it rocks.

Back on linux I followed your build instructions in HowToBuild.md.

First off, I don't like the tone in your forewords here:
"Since I was told that He hadn't known how to build from this source code before"
HE took the time to report. He is actually _helping_ you.

There is no "dependencies" file/list nowhere, and your releases for instance don't include quazip.
(The source archive only contain an empty quazip folder actually).
You might clarify dependencies or provide _complete_ releases if you ever you want distros to pack your (great) soft.

Lastly, source doesn't build here:
I am using gentoo, gcc 5.4.0 and qt: 5.7.1

here is the end of the trace:
https://pastebin.com/STTvzeP2

**Comment by kanryu** [comment]
I am sorry that my sentence is not accurately conveyed to you.
That is an explanation of what I wrote HowToBuild as an answer to your inquiry about the build method. However, there may be problems in expression :(

If you write a more appropriate expression here, let's rewrite it accordingly :)

> Hello Kanryu and thanks for quickviewer: I was able to try it on Windows at work, and apart from systematic crashes when closing, it rocks.

First of all, please tell me whether this problem is occurring in the binary distributed official build.
Since the program which controls multiple processes of QuickViewer has been added since this release, there is a possibility of causing deadlock.

Tar.gz which GitHub automatically generates for each release is not a complete source tree. The submodule is missing. As you can see in HowToBuild, please run 'git submodule update'.

For those that can not be built normally with gcc, please fix it now. Basically QuickViewer is built with msvc, and gcc is occasionally used.

**Comment by Arnaudv6** [comment]
Thanks for the quick reply.
For the forewords (and though I am no English native either), I think something like:
"For those interested in building from source, here is howto:" would very well do.
But quite frankly, I think as long as building involves 3 git lines, no need to justify why you give instructions!

On windows, I was using QuickViewer-0.8.5-x64.zip from the release tab,
and your point about multiple processes certainly certainly explains it.
Though I can not yet try another version for I am on holidays now.

Thanks for the support!

**Comment by kanryu** [comment]
> But quite frankly, I think as long as building involves 3 git lines, no need to justify why you give instructions!

Because I can not understand this sentence accurately, will not you rewrite it to another expression?

About there is not complete source code in some GitHub repository, because git repositories are actively using submodules. So I think I have no choice but to do so.

**Comment by kanryu** [comment]
I have checked on Ubuntu 16.04.2 x64 with Qt 5.8.0

So, please checkout again :)

**Comment by Arnaudv6** [comment]
> But quite frankly, I think as long as building involves 3 git lines, no need to justify why you give instructions!

I guess I could rephrase this sentence like it:
_"Build instructions never hurt. They can help. This is a sufficient motive to provide them.
Plus build steps actually are not so simple since they involves 3 git lines."_

It is plain though that you meant no harm, and you seem a very nice person.

Then... I was able to build quickviewer on gentoo... Wow ! It **is** fast.
I still encounter crashes when quickly navigating between images.
But this will improve as the multi-processing progresses I guess.

Finally, when it comes to releases and submodules,
I am no developper, just a hobbyist, but I guess you have to choose:

- Either each quickviewer releases should dynamically link against submodules and precise which versions it is compatible with.

- Or quickviewer source releases would have to include all submodules.

This is so quickviewer can be built from source at given revision.

**Comment by kanryu** [comment]
I was relieved to hear that you successfully built and run QuickViewer on Gentoo :)
Please write down here if you have anything you noticed before you can build and run.

As for the case of a crash when switching images, it improved by 0.8.7, but it may still be left.

If WorkerThreads attempts to terminate the application before loading the image is over, there is a possibility of a crash, but that has not been fixed yet.

Include complete source code in the tarball of the source code you claim, or about that alternative:

- In the first place, tarball is automatically generated and attached by GitHub, not by the author of each repository manually.
- As in HowToBuild, it is assumed that the build procedure clones from the repository rather than the tarball on the Release page.
- Project management in the git era (especially in third parties) is basically divided into submodules for external projects.

**Comment by Arnaudv6** [comment]
Ok, and thanks for the support.
I hope that major linux distributions can integrate your fast soft one day.
I am closing the bug.
