### ISSUE TITLE
Next Page action not working if image zoomed in

### ISSUE THREAD

**Issue by xd1986k** [kanryu/quickviewer#27]
If image is zoomed in, the scroll up/down only scrolls the image. Would it be possible to make it switch images upon scrolling to the end/beginning of a zoomed-in image.
Thank you.

**Comment by kanryu** [comment]
Previous QuickViewer actually did such behavior, but obviously it was inconvenient.
Because it is very difficult to scroll to the top or bottom of the image naturally with the mouse wheel.

In the current QuickViewer, the mouse wheel scrolls only when the image can be scrolled, and the image switching does not occur.

However, you can switch images with other input methods. For example, entering a keyboard, pushing a button on the toolbar, pressing the 'forward' or 'return' button of the mouse. You can also define other ways if you want :)

**Comment by Hrxn** [comment]
Yeah, agree that this is a bit inconvenient..

What you can do in the meantime, bind the "fitting" option to middle mouse button for example, so you can turn this on or off quickly and also switching between scroll-up/scroll-down and next-image/previous-image with the mouse wheel at the same time.

**Comment by kanryu** [comment]
try 'Ctrl + Middle click' or 'Right click + Middle click' :)

**Comment by Hrxn** [comment]
Yes, I've swapped that one with the 'Fullscreen' switch in my settings.
