### ISSUE TITLE
Crash on incorrect file

### ISSUE THREAD

**Issue by GitHubRulesOK** [kanryu/quickviewer#35]
if a file, folder, sub-folder or zip contains a file with incorrect type (any of these 4 cases)
quickviewer will crash where other apps report incorrect file type

as an example I tried opening a folder that contained sample.pdf that was incorrectly named as sample.png

**Comment by kanryu** [comment]
Thank you for your report.

This problem will be fixed on next release.

**Comment by GitHubRulesOK** [comment]
I am impressed at the speed with which you resolve issues
I was unable to run versions 0.8 due to hardware issues (intel mobile drivers on touchscreen)
However 0.9 is generally stable except for these odd files which took a while to spot the cause as there was no warning. I had to move files around and use a binary chop to find the offending file.

**Comment by kanryu** [comment]
Improved behavior in 32 bit environment with v 0.8.9, and stopped using OpenGL in v 0.9.3. With these changes QuickViewer started running more consistently.

A retry was implemented when the image was not able to be read correctly by v0.8.9 correction, but it caused a stack overflow because it is a recursive call.

This issue will not occur in the next release as we set an upper limit for retries.

**Comment by kanryu** [comment]
@GitHubRulesOK I made it :)

**Comment by GitHubRulesOK** [comment]
Bug as reported is corrected does not crash (simply shows blank page)

![untitled](https://user-images.githubusercontent.com/12754913/30667292-f51464de-9e4e-11e7-87bc-525b52b5f366.png)
