### ISSUE TITLE
Is Lanczos shader removed in the newer versions?

### ISSUE THREAD

**Issue by thewan056** [kanryu/quickviewer#36]
Hi,

Is Lanczos shaders removed from the latest versions? I don't see it anymore under shaders.

Thanks.

**Comment by kanryu** [comment]
Yes, It was removed on v0.9.3 .

This is because OpenGL makes little contribution to drawing speed in normal image display and noticed that normal drawing (GDI) is sufficient. Also, in many cases bicubic interpolation by CPU is better than interpolation with a combination of OpenGL and Lanczos Shader.

If you have never run Lanczos Shader please download v 0.9.2.
