### ISSUE TITLE
Open Image Folder : Sort by "Last modified" instead of "Alphabetic"

### ISSUE THREAD

**Issue by sebastienbo** [kanryu/quickviewer#55]
Open Image Folder : Sort by "Last modified" instead of "Alphabetic"

Hi,

I'm having an issue.
When I'm opening a folder it mixes all my images because the application sorts by Alphabetic order only.
When I use windows photo viewer it is mire intuively, it sorts by last modified date.
Can the ordering be adapted in one of the menus?

**Comment by kanryu** [comment]
The display order of the images in QuickViewer is fixed in file name order (Abc).

Even if it is a book page or even a picture taken with a digital camera, it is a sequential number with the file name, because the timestamp of the file will not be in the correct order.

**Comment by GitHubRulesOK** [comment]
This is a common historic issue as some software looks a different file attributes (creation time, modified time alpha name e.g. 89 before 9 etc, 
It can be worked around using a renamer to prefix files e.g. photos based on dates so 17-12-01_10-AM_replacedfilesource.ext will come after 17-12-01_09-AM_modifiedfile.ext
This may be considered a fudge by some but its good practice in data libraries to ensure files with modified attributes are fixed in date order no matter what the application
