### ISSUE TITLE
Can't open .dds files in version 1.0.6

### ISSUE THREAD

**Issue by Knallertton** [kanryu/quickviewer#58]
Not sure if i am missing a option or something but the program doesn't open .dds files like advertised.
I just get this error "_Image file not found. Can't be opened_". It also skips .dds files if they are in folders with other image types.

I would love this program, since ifran viewer is really slow to open when there is large amount of images in a folder.

**Comment by kanryu** [comment]
Hi,
Please tell me the OS on which you are running QuickViewer. Linux does not include the imageformats plugin for dds and can not be opened.

In the case of Windows, although it should be able to be opened by specification, it may be necessary to modify the program so that it can be opened properly.

**Comment by Knallertton** [comment]
Ah that sucks. I looked up what was the last version that can use .dds format, it's 0.9.2
Thanks for this great program!

**Comment by kanryu** [comment]
Perhaps by copying the plugin from the old version of QuickViewer's imageformats to the latest version of QuickViewer, both will be able to display dds :)

**Comment by Knallertton** [comment]
That worked! Thanks :+1:
