### ISSUE TITLE
Need to be able to pan after zoom

### ISSUE THREAD

**Issue by Gitoffthelawn** [kanryu/quickviewer#8]
After zooming an image, the user cannot pan the image.  This is important! :)

**Comment by kanryu** [comment]
For example, do you want to move the magnified image by dragging the window with the mouse?

Sorry.
Because my knowledge of Qt is insufficient, I need to investigate additional because I want to find out how it can be realized.
Currently, since scroll bars should be displayed when enlarging, please use it.

**Comment by Gitoffthelawn** [comment]
Thanks for investigating. :)

There is a bug in QuickViewer that, when zoomed, it is impossible (even with the scroll bars) to view the leftmost portion of images.

**Comment by kanryu** [comment]
@Gitoffthelawn

I made it :)

**Comment by NXij** [comment]
The panning works now, though the issue where the left side of the image gets cut off and extra not needed scrollable whitespace appears on the right still exists

**Comment by kanryu** [comment]
@NXij 
Thanks. I will fix on next release :)

**Comment by Gitoffthelawn** [comment]
Thank you!  This is really starting to look good (and fast)!
