### ISSUE TITLE
ubuntu 18.04: compile fails

### ISSUE THREAD

**Issue by revast** [kanryu/quickviewer#88]
inux-g++ -o fileoperator.o ../../QuickViewer/src/models/fileoperator.cpp
../../QuickViewer/src/models/fileoperator.cpp: In constructor ‘FileOperator::FileOperator(QString, QObject*)’:
../../QuickViewer/src/models/fileoperator.cpp:10:19: error: variable ‘QJsonDocument docc’ has initializer but incomplete type
     QJsonDocument docc = QJsonDocument::fromVariant(json);
                   ^~~~
../../QuickViewer/src/models/fileoperator.cpp:10:41: error: incomplete type ‘QJsonDocument’ used in nested name specifier
     QJsonDocument docc = QJsonDocument::fromVariant(json);
                                         ^~~~~~~~~~~
../../QuickViewer/src/models/fileoperator.cpp:11:17: error: variable ‘QJsonObject doc’ has initializer but incomplete type
     QJsonObject doc = docc.object();
                 ^~~
../../QuickViewer/src/models/fileoperator.cpp:12:16: error: variable ‘QJsonValue as’ has initializer but incomplete type
     QJsonValue as = doc["as"];
                ^~
../../QuickViewer/src/models/fileoperator.cpp:16:16: error: variable ‘QJsonValue mode’ has initializer but incomplete type
     QJsonValue mode = doc["mode"];
                ^~~~
../../QuickViewer/src/models/fileoperator.cpp:22:16: error: variable ‘QJsonValue command’ has initializer but incomplete type
     QJsonValue command = doc["command"];
                ^~~~~~~
../../QuickViewer/src/models/fileoperator.cpp: In member function ‘QVariant FileOperator::toVariant()’:
../../QuickViewer/src/models/fileoperator.cpp:28:34: error: return type ‘class QVariant’ is incomplete
 QVariant FileOperator::toVariant()
                                  ^
../../QuickViewer/src/models/fileoperator.cpp:30:17: error: aggregate ‘QJsonObject obj’ has incomplete type and cannot be defined
     QJsonObject obj;
                 ^~~
../../QuickViewer/src/models/fileoperator.cpp:36:19: error: variable ‘QJsonDocument doc’ has initializer but incomplete type
     QJsonDocument doc = QJsonDocument(obj);
                   ^~~
../../QuickViewer/src/models/fileoperator.cpp:36:42: error: invalid use of incomplete type ‘class QJsonDocument’
     QJsonDocument doc = QJsonDocument(obj);
                                          ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:54:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                 from ../../QuickViewer/src/models/fileoperator.h:4,
                 from ../../QuickViewer/src/models/fileoperator.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:1881:1: note: forward declaration of ‘class QJsonDocument’
 QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^
Makefile:1494: recipe for target 'fileoperator.o' failed
make[1]: *** [fileoperator.o] Error 1
make[1]: Leaving directory '/media/vault/compiles/quickviewer/quickviewer/build/QuickViewer'
Makefile:209: recipe for target 'sub-QuickViewer-make_first' failed
make: *** [sub-QuickViewer-make_first] Error 2

With git master... how do I compile the release tar when I am supposed to do the git submodule stuff??

also, I cannot open raw images with appimage version

**Comment by kanryu** [comment]
@revast I commited :)

**Comment by revast** [comment]
ok will try asap ;-)

**Comment by kanryu** [comment]
@revast you should run the below.

    $ make install

To see detail for https://github.com/kanryu/quickviewer/blob/master/HowToBuild.md

**Comment by kanryu** [comment]
@revast  @kah0922 It is supported about QV_PORTABLE

If you build on Linux with QV_PORTABLE undefined, it tries to install under /usr/local/bin of the system. Because Qt-related libraries and configuration files use those of the system, we recommend using system-standard Qt instead of Qt SDK.

**Comment by kah0922** [comment]
That helped a lot. Now, for packaging purposes, I had to use sed to move everything from /usr/local to /usr. While this worked for the most part, lib7z.so seems to only want to be found in /usr/lib. I tested this by symlinking lib7z.so from /usr/lib64 to /usr/lib and the library loaded. This is a problem, as for 64bit systems, libraries are installed in /usr/lib64. Even if one were to install something in /usr/local, for 64bit libraries, they would be in /usr/local/lib64.

For the record, you can find the package I'm trying to build [here](https://build.opensuse.org/package/show/home:kah0922:test/quickviewer). The package will compile, but archive loading is broken due to the missile lib7z.so

**Comment by kanryu** [comment]
Normally, on Unix, applications that you build yourself are installed in /usr/local/bin.
However, you seem to be setting up as part of opensuse. If the application is included in the distribution, it will be installed in /usr/bin. If you modify the current quickviewer.pro recipe a bit, it will be a tool to create packages for major distributions.

You can change it if you want to use lib7z on your system. I will add a switch later.

**Comment by kanryu** [comment]
First, the switch that switches between lib7z.so and 7z.so is USE_LIB7Z_DLL.

Next, 7z.so is a special shared library specifically designed for runtime loading, and it is not possible to specify the read PATH with the linker.

The read sequence is fixed, if the environment variable P7ZIP_HOME_DIR is specified, it tries to open 7z.so in that directory, otherwise it tries to open it from the current directory.

Although it is necessary to describe it in the main function of main.cpp, since it is easy to register environment variables with qputenv(), is not it good to insert code?
